modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="enchantmentsplusplus_redux"
version="1.0.0"
displayName="Enchantments++ Redux"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="SparkleArts"

[[dependencies.enchantmentsplusplus_redux]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.enchantmentsplusplus_redux]]
    modId="simpleconfig"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantmentsplusplus_redux]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

